---
apiVersion: v1
kind: Service
metadata:
  name: kcp
spec:
  ports:
    - protocol: TCP
      name: kcp
      port: 6443
      targetPort: 6443
  selector:
    app: kcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcp
  labels:
    app: kcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kcp
    spec:
      containers:
      - name: kcp
        image: ghcr.io/kcp-dev/kcp:latest
        ports:
        - containerPort: 6443
        command:
        - /kcp
        args:
        - start
        - --etcd-servers=etcd0:2379
        env:
        - name: EXTERNAL_HOSTNAME
          value: kcp
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: livez
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: readyz
            port: 6443
            scheme: HTTPS
        resources:
          requests:
            cpu: '1'
            memory: 1Gi
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kcp/config
      volumes:
      - name: kubeconfig
        hostPath:
          path: /kcp
